### ISSUE TITLE
on 2020.11.14 task

### ISSUE THREAD

**Issue by agricolamz** [ruthenian8/bagvalal#1]
* Numeral *це=в*, *це=й*, *це=б* 'one' is not covered. There are wrong forms *цубда* and *цебдала* instead.
* Here we need @nlhowell's help on how combine several stems together (e. g. *ч1ац1а* '2-10')
* Add Kibrik's missed forms
* -*da/ra* is a numeral marker. Gloss it as `<num>`
* -*la* is a collective numeral marker. Gloss it as `<coll>`
* I'd gloss *hats'a* and *ts'a* as ten. I'm against `<*10>` gloss.
* Numeral five is *инщтуда*, not *инщтудда*
* Forms *гьацӀ* and *гьацӀа* shouldn't be generated. Only with other numerals.
* *чӀекӀуб* should be glossed as `<lnk>`
* Add POS tag `<num>`

**Comment by nlhowell** [comment]
Garik wrote:
> * Here we need @nlhowell's help on how combine several stems
> together (e. g. *ч1ац1а* '2-10')

Well, I cannot say that I like the gloss, but it appears to work:
```
$ lexd bagval_numbers.txt | hfst-txt2fst | hfst-invert -o analyse.hfst
$ echo 'чӀацӀа' | hfst-lookup analyse.hfst
> чӀацӀа	2<*10>	0.000000
```

@agricolamz, was there something else you expected?

**Comment by agricolamz** [comment]
I'd like to have stems (ч1а<num>-гьац1а<num>). That is back to our discussion what do we want to have in analysis: glosses or lemmata. For now it like analyze *триста* as three-hundred that you disprefered earlier.

**Comment by nlhowell** [comment]
Sorry for the slow reply; usually Github sends me an e-mail when
someone responds to me :(

> I'd like to have stems (`ч1а<num>+гьац1а<num>`, `+` is a morpheme
> boundary).

I agree with this as the preferred format for glossing; we may have to
worry about the distinction between "addition" and "multiplication"
morphemes. (I haven't consulted the grammar :3 so I don't know if this
occurs.)
