### ISSUE TITLE
question on negative markers

### ISSUE THREAD

**Issue by ruthenian8** [ruthenian8/bagvalal#5]
It appears, that all nouns and nominalized numbers in bagvalal can come with a negation affix as a part of one certain construction
<img width="1036" alt="subs" src="https://user-images.githubusercontent.com/45140209/102407373-1108d780-3ffd-11eb-8e5a-390d760e1b2a.png">

Does it mean, that we will have to create a pattern for all those cases? Wouldn't it be some sort of overload?

**Comment by nlhowell** [comment]
I think you can just add `Neg?` to your pattern, where `Neg` is a
single-element lexicon with this negation morpheme? The `?` means it
is optional, i.e., there are variants with and without.

**Comment by agricolamz** [comment]
I don't think it is a problem. I'd add this form.

**Comment by ruthenian8** [comment]
Thank you, I will probably implement this in the suggested manner
