### ISSUE TITLE
question on number morphology

### ISSUE THREAD

**Issue by ruthenian8** [ruthenian8/bagvalal#6]
Is it necessary to specify a rule for concatenating nominalized nouns with spatial markers? I suppose that they can cooccur, although such cases ought to be rare.

**Comment by agricolamz** [comment]
could you give some examples? I don't see any problem yet...

**Comment by ruthenian8** [comment]
I mean, it is stated in the grammar that both nominalized adjectives and nominalized numbers can possibly have localization markers
(Выражение категорий
падеж а и локализаци и у субстантивированных прилагательных не имеет
каких-либо отличий от выражения этих категорий у существительных)
yet the examples that are given only include grammatical cases (like the table I included in the previous issue), which is why I wonder if the nominalized numbers with localization markers aren't exceptionally rare. The grammar contains no special comments about that.

**Comment by agricolamz** [comment]
I'd do it anywhay. It is rare. True. But I collected those forms myself, and you can find some of them in the text. There of course won't be such examples like  "2347 came", but if we can infer from the grammar, it is better to describe it.

**Comment by ruthenian8** [comment]
Fine, I'm on it then.
