### ISSUE TITLE
Transliteration problem

### ISSUE THREAD

**Issue by ruthenian8** [ruthenian8/bagvalal#8]
Recently I've been trying to merge the transliteration transducer and the analyzer into one, so that I can process latin-based strings. Whenever I typed hfst-compose or hfst-compose-intersect, I received an error message, which I'm pasting below:

$ hfst-compose-intersect -1 translit.hfst -2 merged.ana.hfst -o tm.ana.hfst
hfst-compose-intersect: warning: Transducer type mismatch in translit.hfst and merged.ana.hfst; using former type as output
Error: hfst-compose-intersect cannot process transducers that are in optimized lookup format.

$ hfst-compose -1 translit.hfst -2 merged.ana.hfst -o tm.ana.hfst
Error: hfst-compose cannot process transducers that are in optimized lookup format.

I have no idea, how to deal with this, so help is much needed

**Comment by mr-martian** [comment]
`hfst-fst2fst -t` will convert from optimized lookup format back to the default format.
