### ISSUE TITLE
Transliteration problem #2

### ISSUE THREAD

**Issue by ruthenian8** [ruthenian8/bagvalal#9]
The main transducer (merged.ana.hfst) uses a cyrillic alphabet. 
to make it one should run the following:
$ make merged.ana.hfst
In order to process latin tokens I intersect the main transducer with a transliteration transducer (translit.hfst)
this step is complete by running the following set of commands: 
$ cd translit
$ make translit.hfst
$ cd ..
$ make merged.tr.hfst
The issue is that the intersected transducer does not process some tokens that are defined in the cyrillic transducer and correctly transliterated by translit.hfst.
For example, translit.hfst correctly transliterates the word "azdaho" as "аздагьо"
The cyrillic transducer (merged.ana.hfst) correctly parses "аздагьо" as "аздагьо\<noun\>\<nom\>"
But the intersected transducer (merged.tr.hfst) does not recognize "azdaho" at all. This affects only some of the latin tokens, but not all of them.
Any suggestions on what could be the reason of this behaviour would be greatly appreciated. I suspected that twol might affect the process, but all of the used cyrillic symbols are present in the twol alphabet.

**Comment by mr-martian** [comment]
```diff
diff --git a/translit/Makefile b/translit/Makefile
index efefe4f..d363891 100644
--- a/translit/Makefile
+++ b/translit/Makefile
@@ -1,5 +1,5 @@
 translit.hfst: translit translit.multi translit-initial.hfst
 #      sed 's/$$/      1/g' <$< | hfst-strings2fst -j -m $<.multi | hfst-repeat | hfst-concatenate translit-initial.hfst - | hfst-fst2fst -w -o translit.hfst
-       sed 's/$$/      1/g' <$< | hfst-strings2fst -j -m $<.multi | hfst-repeat | hfst-concatenate translit-initial.hfst - -o translit.hfst
+       sed 's/$$/      1/g' <$< | hfst-strings2fst -j | hfst-repeat | hfst-concatenate translit-initial.hfst - -o translit.hfst
 translit-initial.hfst: translit-initial
        sed 's/$$/      1/g' <$< | hfst-strings2fst -j -o $@
```
This fixes it for me.

The characters you have listed in `translit/translit.multi` may be logical characters in terms of phonology (I assume that's why you listed them) but they're separate graphemes, so lexd separates them and I see that you also have them separate in twol.

Thus, while the final strings of the analyzer and transliterator matched, the sequence of symbols did not.
